config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :favorites, only:[:create, :destroy]
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only:[:new, :create, :show]
  root to: 'tweets#home'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :tweets do
      collection do
          post :confirm
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :content, presence: true,length: { maximum: 140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :picture, ImageUploader
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save

      ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @tweet_id = params[:tweet_id]
    @user_id = current_user.id
    favorite = Favorite.create(user_id: @user_id,tweet_id: @tweet_id)
    redirect_to tweets_url, notice: "#{favorite.tweet.user.name}さんのつぶやきをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(tweet_id: params[:tweet_id]).destroy
    redirect_to tweets_url, notice: "#{favorite.tweet.user.name}さんのつぶやきをお気に入り解除しました"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only:[:show, :edit, :update, :destroy,]
  before_action :login_check, only:[:new, :edit, :show, :index]

  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end


  def create

    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.picture.retrieve_from_cache! params[:cache][:picture] if params[:cache][:picture].present?
    respond_to do |format|
      if @tweet.save
        TweetMailer.tweet_email(@current_user, @tweet).deliver
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

      #if @post.save
        #TweetMailer.post_email(current_user, @tweet)
        #format.html { redirect_to @post, notice: 'Tweet was successfully created.' }
        #format.json { render :show, status: :created, location: @post }
      #else
        #format.html { render :new }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
      #end
  def home
    @tweet = Tweet.order(:content)
    @tweet = Tweet.limit(10).order(:content)
  end

  def show
    @favorite = current_user.favorites
    @favorite = @favorite.where(tweet_id: @tweet.id)
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "つぶやきを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice:"つぶやきを削除しました！"
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
  end


  private
  def tweet_params
    params.require(:tweet).permit(:user_id, :content, :tweet_id, :picture, :picture_cache)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def login_check
    unless logged_in?
      flash[:notice] = "権限がありません"
      redirect_to new_session_path
    end
  end

  def session_user
    session.session_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_tweets =  @user.favorite_tweets
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture, :picture_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_tweets_path
        elsif action_name == 'edit'
            tweet_path
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="header">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Twitter_clone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">TwitterClone</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="/tweets/new">つぶやく</a>
            </li>
            <li>
              <a href="/tweets">つぶやき一覧</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <p>PHASE2大課題</p>
        <p>2018.03.07</p>
      </div>
    </footer>

  </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, url:choose_new_or_edit, local: true) do |form| %>
    <% if @tweet.errors.any? %>
        <div id="error_explanation">
            <h3><%= @tweet.errors.count %>件のエラーがあります。</h3>
            <ul>
                <% @tweet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <h2 class="text_center">つぶやきを投稿する</h2>
        <div class="tweet_form text_center">
            <%= form.text_field :content ,class:'form-group form-control'%>
            <%= form.hidden_field :user_id, value: current_user.id %>
        </div>
        <div class="tweet_picture">
          <%= form.label :picture %>
          <%= form.file_field :picture, id: :tweet_picture %>
          <%= form.hidden_field :picutre_cache %>
        </div>
        <div class="confirm_button text_center">
            <%= form.submit :'確認画面に進む' ,class: 'btn btn-success' %><span class="glyphicon glyphicon-chevron-right"></span>
            <% end %>
        </div>
<%= link_to "つぶやき一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<%= form_with(model: @tweet, url: tweets_path, local: true)do |form| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
        <h3><%= @tweet.errors.count %>件のエラーがあります。</h3>
        <ul>
            <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<h3 class="text_center">以下の内容で、送信する。</h3>

    <%= form.hidden_field :content %>
    <%= form.hidden_field :picture %>


    <p class="text_center">本文:<%=  @tweet.content %></p>
    <p class="text_center">画像:<%= image_tag (@tweet.picture.url) if @tweet.picture.present? %>
    <%= hidden_field_tag :"cache[picture]",@tweet.picture.cache_name %>
    <div class="send_button">
        <div class="confirm_button text_center">
            <%= form.submit "送信する" ,class: 'btn btn-success' %><span class="glyphicon glyphicon-chevron-right"></span>
        </div>
    </div>
<% end %>


    <div class="back_button">
    <%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
        <div class="confirm_button text_center">
        <%= form.hidden_field :content %>
        <%= form.hidden_field :picutre_cache %>
        <%= form.submit "もどる", name: 'back' ,class: 'btn btn-success' %><span class="glyphicon glyphicon-chevron-right"></span>
    <% end %>
  </div>

app/views/tweets/edit.html.erb
<h2>つぶやきを編集する</h2>

<%= render 'form' %>

app/views/tweets/home.html.erb
<div class="post_link">
    <h1>
        <a href="/tweets/new" class="typewrite" data-period="2000" data-type='[ "140文字以内でつぶやいてみよう！"]'>
            <span class="wrap"></span>
        </a>
    </h1>
</div>


<div class="page_title">
    <h2 class="text_center">最近の投稿</h2>
</div>

<div class="table-responsive hidden-xs clearfix">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>id</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
        <% @tweet.each do |tweet| %>
            <tr>
                <th scope="row"><%= tweet.id %></th>
                <td><%= tweet.content %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
<div class="tweet-panel hidden-lg hidden-mg hidden-sm col-xs-12 clearfix">
    <div class="panel panel-default">
        <% @tweet.each do |tweet| %>
        <div class="panel-container">
            <div class="panel-heading">
                <h3 class="panel-title"><%= tweet.id %></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10">
                        <%= tweet.content %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/tweets/index.html.erb
<div class="main_contents">
    <h1 class="text_center">つぶやき一覧</h1>
        <% @tweets.each do |tweet| %>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><%= tweet.id %></h3>
                </div>
                <div class="panel-body">
                    <%= tweet.content %>
                    <% if current_user.id == tweet.user_id %>
                      <%= link_to '　詳細を確認する　', tweet_path(tweet.id) %>
                      <%= link_to "　つぶやきを編集する　", edit_tweet_path(tweet.id), data: { confirm: '本当に編集していいでいいですか？' } %>
                      <%= link_to '　つぶやきを削除する　', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
                    <% else %>
                      <%= link_to '　詳細を確認する　', tweet_path(tweet.id) %>
                    <% end %>
                </div>
            </div>
        <% end %>
</div>

app/views/tweets/new.html.erb
<%= render 'form' %>

app/views/tweets/show.html.erb
<p><%= notice %></p>
<h1>つぶやき詳細</h1>
<p>内容：<%= @tweet.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @tweet.picture %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %>
<%= link_to 'Back', tweets_path %>

<% unless @tweet.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(tweet_id: @tweet.id), method: :delete,class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(tweet_id: @tweet.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :picture %>
  <%= f.file_field :picture, id: :user_picture %>
  <%= f.hidden_field :picture_cache %>

  <%= f.submit "Create my accont" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス：<%= @user.email %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @user.picture %>
</p>
<% @favorite_tweets.each do |tweet| %>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><%= tweet.id %></h3>
        </div>
        <div class="panel-body">
            <%= tweet.content %>
            <%= link_to '　詳細を確認する　', tweet_path(tweet.id) %>
        </div>
    </div>
<% end %>